export const EVENTS = {
  GAME_STATE_CHANGED: 'GAME_STATE_CHANGED',
  WAVE_CHANGED:       'WAVE_CHANGED',
  COMMAND_CHANGED:    'COMMAND_CHANGED',
  HONOR_EARNED:       'HONOR_EARNED',
  UNIT_DIED:          'UNIT_DIED',
  ELITE_KILLED:       'ELITE_KILLED',
  SCREEN_SHAKE:       'SCREEN_SHAKE',
  UNIT_SPAWNED:       'UNIT_SPAWNED',
};
